apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    name: web-app
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-app-pod
      app: website
  template:
    metadata:
      name: web-app-pod
      labels:
        name: web-app-pod
        app: website
    spec:
      containers:
        - name: web-app
          image: 213749874755.dkr.ecr.eu-west-1.amazonaws.com/osinachiprofile:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
