apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    name: web-app
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-app-pod
      app: website
  template:
    metadata:
      name: web-app-pod
      labels:
        name: web-app-pod
        app: website
    spec:
      containers:
        - name: web-app
          image: public.ecr.aws/c9r2v0m2/osinachiprofile:1.1
          ports:
            - containerPort: 80
